<a href="https://colab.research.google.com/github/nuru1234/Deep-Learning-Churn-Prediction/blob/main/Churn_Prediction_by_Deep_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Churn Prediction with Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.9.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [5]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [6]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [9]:
X[:, 1]

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

### Encoding categorical data

Label Encoding the "Gender" column

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [11]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [13]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [14]:
#After adding Dummy variable, CreditScore column jumped into the 4th column
X[:,3]


array([619, 608, 502, ..., 709, 772, 792], dtype=object)

### Splitting the dataset into the Training set and Test set

In [15]:


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [16]:
#Feature Scaling is compulsory for ANN, for all columns 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [18]:
X_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

In [19]:
y_train

array([0, 0, 0, ..., 0, 0, 1])

In [20]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

## Part 2 - Building the ANN

### Initializing the ANN

In [21]:
#Creating ANN variables which represents ANN as an instance of the sequential class which initializes ANN
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [22]:
#Anything can be added whether it is a hidden layer or dropout layer, that prevent overfitting .
#Adding a simple and fully connected layer.
#'add' method is way of adding fully connected layer that will br a new object.It is gonna be a new instance of a new class.
#And a new class is the dense class.
# So fully connceted layer we are about to build will be created as an object of the dense class.
# After then it will automatically add the input layer.
#
#How do we konow how many neurons('units' below) we want?There is no rule of thumb. 
#It is just based on experimentation or we call it the work of an artist.
# And you have to experiment with different hyperparameters
#relu : rectifier activation function

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [24]:
ann

### Adding the output layer

In [25]:
#there is one output neuron, thw will be 1 for 'units' paramter

#Activation function of the output layer doesn't nee to be 'relu' but sigmoid activation function. 
#As to why to choose sigmoid function is that
# sigmoid activation function allows to get not only ultimately the predictions but even better , 
#it is gonna give you the probabilities that the binary outcome
# so that we will not not only get the predictions of whether the customers choose to leave or not the bank 
# but we will also have for each customer the probability
# that the customer leaves the bank and all this thanks to that sigmoid activation function
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [26]:
#It will be began from the ANN object  that reminds creating as an instance of the sequential class, 
#and then which this time , of course , won't be add method
#The method to compile is the 'compile' method

#For optimizer, we choose 'adam' optimizer , that is performance optimizer that can perform the Stochastic Gradient Descent. And by that, 
#Stochastic Gradient Descent update the weights in order to reduce loss error between predictions and actual values
#At each iteration, it compares the predictions in a batch to the real results in the same batch.

# 'loss' is computing differences between the predictions and actual values, as it is a final evaluation metric
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [27]:
# batch learning is always efficient more performance when training ANN.
# 'batch_size' >> gives exactly the number of predictions we want to have in the batch to be compared to to that same number of real results.

#The classic value of batch size is usualy chosen as 32, 

#The neural network needs a certain amount of epochs in order to learn properly, learning correalations to get the ultimate best predictions.

ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6439 - accuracy: 0.6597
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4753 - accuracy: 0.7977
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4463 - accuracy: 0.7999
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4329 - accuracy: 0.8031
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4254 - accuracy: 0.8046
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4193 - accuracy: 0.8067
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4115 - accuracy: 0.8114
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4000 - accuracy: 0.8223
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3865 - accuracy: 0.8345
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3756 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**An Example of Customer in a Bank**

With the information below, let's predict whether a customer will leave the bank: 

Geography: France

Credit Score: 600

Gender: Female

Age: 50 years old

Tenure: 3 years

Balance: \$ 40000

Number of Products: 5

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 80000

So, should we say goodbye to that customer?

**Solution**

In [28]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 0, 50, 3, 40000, 5, 1, 1, 80000]])) > 0.5)

1/1 [==============================] - 0s 97ms/step
[[ True]]


Therefore, our ANN model predicts that this customer leaves in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [29]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

#1508 cutomer are correctly predicted 'stay in the bank', 208 correct predictions as 'customers leave the bank'
# 87 incorrect predictions that customers leave the bank and 197 incorrect predictions that customer stay in the bank

[[1508   87]
 [ 197  208]]


0.858